apiVersion: v1
kind: Service
metadata:
  name: coworking
spec:
  type: LoadBalancer
  selector:
    service: coworking
  ports:
  - name: "5432"
    protocol: TCP
    port: 80
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
  labels:
    name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
      - name: coworking
        image:<> ,..,.,.,<><><><>><><><><><>>
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: "/api"
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/api"
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: cowarking-configmap
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cowarking-secret
              key: DB_PASSWORD
      restartPolicy: Always